fix RuntimeException
java.lang.RuntimeException: Unable to create application imoblife.toolbox.full.App: java.lang.NullPointerException
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4525)
at android.app.ActivityThread.access$1500(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1306)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5212)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.app.ContextImpl.getTheme(ContextImpl.java:714)
at android.content.ContextWrapper.getTheme(ContextWrapper.java:125)
at android.content.Context.obtainStyledAttributes(Context.java:391)
at org.holoeverywhere.ThemeManager.getThemeType(ThemeManager.java:402)
at org.holoeverywhere.app.Application.onCreate(Application.java:116)
at imoblife.toolbox.full.App.onCreate(App.java:12)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1008)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522)
... 10 more

https://play.google.com/apps/publish/?dev_acc=17736375203683117254#ErrorClusterDetailsPlace:p=imoblife.toolbox.full&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=ContextImpl.java&tc=android.app.ContextImpl&tm=getTheme&nid&an&c&s=reports_last_week_desc